image: docker:19.03.11

services:
  - docker:19.03.11-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  HV_REF_POINT: "[1, 1]"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

test-docker:
  stage: test
  script:
    - docker build --tag best:latest .
    - 'echo {\"objective\": 1} > f1'
    - 'echo [{\"score\": 3}, {\"score\": 2}] > f2'
    - docker run -v $(pwd):/usr/src/app best:latest f1 f2
    - 'echo {\"objective\": 2} > f1'
    - 'echo [{\"score\": 3}, {\"score\": 1}] > f2'
    - docker run -v $(pwd):/usr/src/app best:latest f1 f2

test-py35:
  stage: test
  image: python:3.5-slim
  before_script:
    - echo $SHELL
  script:
    - 'python best.py <(echo {\"objective\": 1}) <(echo [{\"score\": 3}, {\"score\": 2}])'
    - 'python best.py <(echo {\"objective\": 2}) <(echo [{\"score\": 3}, {\"score\": 1}])'
